### PR TITLE
Add install and use description

### PR DESCRIPTION
**Pull request by LM1LC3N7**
Hi @AioiLight ,

Thank you for your free and open source plugin. It works very well on my side.

I have updated your Readme file to explain how to install and use your plugin. You can accept my pull request if you want, I am sure it will help people to use your work 😃 

I found one "limitation" or UI improvement: during export using your plugin, Lightroom does not show the progress of the export, like it does using a regular export task. It is not a problem but users must now that (that it why I have added it at then end of the Readme).

### CODE REVIEW

**Comment by AioiLight** [comment]
Hello :)

Sorry for after writing, I add a release of GitHub feature, Can you rewrite README article?
https://github.com/AioiLight/AL-SameFolderStructre/releases

I decide looking for how to show exporting progress.

**Comment by LM1LC3N7** [comment]
You still can approve my pull request to merge it to master. It does not depend on any release. A release is just your code on a specific time.

**Comment by AioiLight** [comment]
I thought it is better to download from Releases than to download main branch because Releases don't have unnecessary files (i.g. .gitignore).

**Comment by LM1LC3N7** [comment]
Indeed I forget I mentioned downloading the full GitHub project on the my Readme edit.
It is corrected now, I just mention the release page.

**Comment by AioiLight** [comment]
Thank you. Looks good!

**Pull request merged**
